### ISSUE TITLE
United Kingdom Financial Information

### ISSUE THREAD

**Issue by Heiwa1580** [Glimesh/company#4]
Here is information regarding the UK and the tax treaties in place. 

https://www.irs.gov/businesses/international-businesses/united-kingdom-uk-tax-treaty-documents

We need to determine the following

- US Withholding Taxes for UK streamers
- Sales Tax for subscription
- Anything else?

**Comment by enixlabs** [comment]
"VAT" is a bit of a dodgy area when it comes to "Subscriptions", however you are required under UK law to be VAT registered in the UK if access to sales or purchase is required, this would also be the same in the EU also.

https://www.gov.uk/guidance/clubs-and-associations-vat-responsibilities-notice-7015

There is plenty of advice and help on this site in regards to "VAT"

http://plvat.co.uk

In regards to US Withholding Taxes for the UK, we have a "Double Tax" treaty with the US, where the taxable rate is dropped from 30% to 15%. Twitch provides access to a "W-8BEN" form for this process, which as the user you are required to fill out and submit in order to only face 15% and not 30%.

Now there is a further issue in regards to this and it concerns "Self Employed" status in the UK and what is currently known as IR35. 

https://www.gov.uk/guidance/understanding-off-payroll-working-ir35

I would highly recommend that the use of "Contractors" is seriously looked at by Glimesh, as Mixer was and Twitch is in breach of UK law on this, due to the terms of the contracts we have to sign. If you put any limitations into a contract for a UK streamer, you are effectively making them a "PAYE". This makes you as a "Foreign" company, liable under "Employment Law", as any restriction on a contractor in terms of what they do as a streamer **IE: Have to be streaming a minimum amount of time per week** This is a restriction in contractual obligations and recently in the UK, many cases have been won and many are still going through and due to be won, as this is a classification of "Employment".

I would also highly recommend that Glimesh seriously look at getting full legal team together, as it will cover all these areas and any further obligations across international law, as well as US law and other countries of operations laws as well.

**Comment by Heiwa1580** [comment]
Do you know if Twotch issues a 1042S at the end of the year?

**Comment by enixlabs** [comment]
Never been issued one
