### ISSUE TITLE
Preform another streamer survey

### ISSUE THREAD

**Issue by clone1018** [Glimesh/company#9]
I want to send one final streamer survey out to the world so we can get an idea of who would be using our platform on launch. I'm wanting to add any new questions we want to get that would help us understand how we should be scaling our infrastructure for launch day. Previously we asked:

* How many average viewers do you have?
* How many subscribers do you have?
* How many hours a day do you stream?
* How many days a week do you stream?
* What bitrate do you stream at? (kbps)
* Do you offer multiple resolutions of your stream (transcoding)? 

What other questions should we ask? I think we want to focus on items that give us good aggregate data, think in numbers instead of word responses.

**Comment by Heiwa1580** [comment]
Perhaps something to identify general location to determine where we need servers?

**Comment by KruxGamingTV** [comment]
How many average viewers do you have? 2.2
How many subscribers do you have? 0 But hope to have more with glimesh
How many hours a day do you stream? I make my own schedule due to requirements but plan on doing it part time
How many days a week do you stream?I make my own schedule due to requirements but plan on doing it part time
What bitrate do you stream at? (kbps) 1500
Do you offer multiple resolutions of your stream (transcoding)? Yes
